### ISSUE TITLE
bomtrace2 writing to the wrong file?

### ISSUE THREAD

**Issue by RobMarion** [omnibor/bomsh#23]
_I tried:_
/bomsh/src$  ../bin/bomtrace2 make
gcc -c -o hello.o hello.c
gcc -o hello hello.o

then
more /tmp/bomsh_hook_raw_logfile
	_and I get an empty file_
/tmp/bomsh_createbom_jsonfilec is also empty

**BUT** in the /tmp/bomsh_hook_raw_logfile.sha1 file, I get the expected output
@yonhan3

**Comment by yonhan3** [comment]
Hi R Marion,

Yes, that is expected.

Previously bomsh/bomtrace2 only supports SHA1, thus no need for that .sha1 suffix.

Later, SHA256 hash support was added, thus we added .sha1 or .sha256 suffix for the bomsh_hook_raw_logfile.

Let me try to update the README file in my next commit to bomsh.

Thanks,
Yongkui

From: R Marion ***@***.***>
Date: Tuesday, April 11, 2023 at 6:07 PM
To: omnibor/bomsh ***@***.***>
Cc: Yongkui Han (yonhan) ***@***.***>, Mention ***@***.***>
Subject: [omnibor/bomsh] bomtrace2 writing to the wrong file? (Issue #23)

I tried:
/bomsh/src$ ../bin/bomtrace2 make
gcc -c -o hello.o hello.c
gcc -o hello hello.o

then
more /tmp/bomsh_hook_raw_logfile
and I get an empty file
/tmp/bomsh_createbom_jsonfilec is also empty

BUT in the /tmp/bomsh_hook_raw_logfile.sha1 file, I get the expected output
@yonhan3<https://github.com/yonhan3>

**Comment by yonhan3** [comment]
Hi R Marion,
 
I have updated the README.md in the below repo (which will be merged to the main repo soon):

https://github.com/yonhan3/bomsh/tree/umbrella-pid-feature

Let me know if there is anything more for me to update.

Here is the pull request: https://github.com/omnibor/bomsh/pull/24
You are very welcome to leave comments in the PR above.

BTW, the default of the bomsh_hook2.py script is to generate SHA1 only, but you can use "--hashtype sha1,sha256" option to generate both SHA1 and SHA256. Also you can use "--hashtype sha256" option to generate SHA256 only.

Thanks,
Yongkui

**Comment by RobMarion** [comment]
Thank you Yongkui. One question (and this may be me) but bomsh_createbom_jsonfile was empty. Of course, it is possible I may have made a mistake.

**Comment by yonhan3** [comment]
Hi Rob, did you run the below command to generate the bomsh_createbom_jsonfile?
../scripts/bomsh_create_bom.py -r /tmp/bomsh_hook_raw_logfile.sha1 -b /tmp/bomdir
Before running this command, make sure that your bomsh_hook_raw_logfile.sha1 file is generated successfully.
