### ISSUE TITLE
Having issues getting bomsh to run

### ISSUE THREAD

**Issue by nellshamrell** [omnibor/bomsh#9]
Hello all!

I'm having some trouble getting results from bomsh (and the other binaries created from this repo). I haven't been successful with any of the examples, this is the one I'm currently on:

It's the one in the README under "If you need to generate gitBOM docs for another software like OpenSSL,"

I created the bomsh binaries with:

```bash
$ git clone https://github.com/git-bom/bomsh.git
$ cd bomsh
$ docker run -it --rm -v ${PWD}:/out $(cd .devcontainer && docker build -q .)
```

This created the bombash, bomtrace, and bomtrace2 binaries in my bomsh directory. I then moved those binaries into the bin folder like this:

```bash
(in bomsh directory) $ mv .bombash ./bin
```

Then I attempted to run the OpenSSL example with:

```bash
$ rm -rf /tmp/bomdir; rm /tmp/bomsh_hook_*; cp scripts/bomsh_hook.py /tmp
$ git clone https://github.com/openssl/openssl.git
$ cd openssl
$ ./Configure
$ BOMSH=../bomsh/bin/bombash
$ make
```

I then attempted to run:

```bash
$ ls -tl /tmp/bomdir
```

but got back the error `ls: cannot access '/tmp/bomdir': No such file or directory`

Additionally, when I tried to run the next instruction:

```bash
$ cat /tmp/bomsh_hook_jsonfile
```

But that file does not exist on my system.

Is it possible there is a step that is missing?

**Comment by nellshamrell** [comment]
Additional info:

I am running this on Ubuntu 20.04

I am also running Python 3.8.10

**Comment by yonhan3** [comment]
I would suggest to try the below steps with bomtrace2:

$ git clone https://github.com/git-bom/bomsh.git
$ cp bomsh/scripts/bomsh_*.py /tmp
$ git clone https://github.com/openssl/openssl.git
$ cd openssl
$ ./Configure
$ ../bomsh/bin/bomtrace2 -c ../bomsh/bin/bomtrace.conf -w ../bomsh/bin/bomtrace_watched_programs make
$ ../bomsh/scripts/bomsh_create_bom.py -r /tmp/bomsh_hook_raw_logfile -b /tmp/bomdir
$ ls -tl /tmp/bomdir/objects /tmp/bomdir/metadata/bomsh
$ cat /tmp/bomsh_hook_raw_logfile
$ cat /tmp/bomsh_createbom_jsonfile

Let me know if this works for you.

**Comment by yonhan3** [comment]
I found the root cause of this BOMBASH issue. I will fix it in my next commit.

In the meantime, please try the suggestion using bomtrace2.

Thanks for reporting this issue.

**Comment by nellshamrell** [comment]
ty @yonhan3!
